name: Update Google Scholar Citations Badge

on:
  schedule:
    - cron: "0 0 * * *"   # 每天更新一次
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run citation update script
        run: python fetch_citations.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add citations.json
          git commit -m "Update citations badge" || echo "No changes to commit"
          git push
